apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-lookup-another
  description: Artist Lookup
  annotations:
    circleci.com/project-slug: github/pkman92/grpc-spring-spring
    backstage.io/techdocs-ref: value
    github.com/project-slug: 'pkman92/backstage'
    'backstage.io/kubernetes-id': artist-lookup-another
    aws.com/lambda-function-name: serverlessrepo-hello-world-helloworld-4fKxsXN8Nszz
    aws.com/lambda-region: us-east-1
  tags:
    - java
    - data
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: artist-engagement-portal
  dependsOn: ['resource:artists-db']
