apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ui-dist
  description: UI Dist asset
spec:
  type: service
  lifecycle: experimental
  system: shipping-service
  dependsOn:
    - Component:default/yarn
